### ISSUE TITLE
Ability to test and contribute

### ISSUE THREAD

**Issue by jimianelli** [imarpe/jjmTools#1]
Hi,

I've been using the jjmtools from last year and would like to contribute and collaborate on enhancements.

For example, I applied the package to a simple case study for chub mackerel in Korea and found a couple of apparent bugs...

Thanks
Jim

**Comment by roliveros-ramos** [comment]
Hi Jim, we sent you an invite to the sprfmo group, so you can push changes. We'll start to use the issues feature to list the to do work. Feel free to open more issues .
